# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvoyCli < Formula
  desc "A tool for debugging convoy webhook events locally"
  homepage "https://getconvoy.io/"
  version "0.0.4"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.0.4/convoy-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "7b74519163d001615d0cfee83161a9b31d28cea58a0359f7268e952ab3e0872d"

      def install
        bin.install "convoy-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.0.4/convoy-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "f2f724d4cb91e0a4642845122471e3b501b7ee81ce2e242fc97ba36644b8c853"

      def install
        bin.install "convoy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.0.4/convoy-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "5f9bf093e2405e29762622e17cf15eeb8e40a4f0b6e13169f12d00c237001805"

      def install
        bin.install "convoy-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.0.4/convoy-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "843c3ad4719561c8608eb2223c51b6227fa9f4341e73072942bee0294f0a988d"

      def install
        bin.install "convoy-cli"
      end
    end
  end
end
