# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConvoyCli < Formula
  desc "A tool for debugging convoy webhook events locally"
  homepage "https://getconvoy.io/"
  version "0.1.0"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.1.0/convoy-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "51c2ffbacf8ffaf6a41c65e034349c18417b5ea68ea5f49a3b47fe1a9a3c6d40"

      def install
        bin.install "convoy-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.1.0/convoy-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4d03bf15ffa0229c3303c2e78bd9cf9727f6424c4d81914efe3e87c6f8d7a15e"

      def install
        bin.install "convoy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.1.0/convoy-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "0db6951529d4646d95c074779be52fa90418192f546ee0f1832a3d99be893e23"

      def install
        bin.install "convoy-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://dl.cloudsmith.io/public/convoy/convoy-cli/raw/versions/0.1.0/convoy-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "292dcf280b7f22873db1952407b528d43a0aee59cb3f7d5fce0cdfdfcceca5d9"

      def install
        bin.install "convoy-cli"
      end
    end
  end
end
