# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Convoy < Formula
  desc "A fast & secure open source webhooks service"
  homepage "https://getconvoy.io/"
  version "25.7.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dl.cloudsmith.io/public/convoy/convoy/raw/versions/25.7.1/convoy_25.7.1_darwin_amd64.tar.gz"
      sha256 "7cea7aeb6402d1c5b84fdd1b834c1b30797a67441199a1b2dca2f5e7c7218f68"

      def install
        bin.install "convoy"
      end
    end
    if Hardware::CPU.arm?
      url "https://dl.cloudsmith.io/public/convoy/convoy/raw/versions/25.7.1/convoy_25.7.1_darwin_arm64.tar.gz"
      sha256 "f1631922f1611c19398c5426bd993cb766acb1c2f50598e1d428179af854b6d3"

      def install
        bin.install "convoy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://dl.cloudsmith.io/public/convoy/convoy/raw/versions/25.7.1/convoy_25.7.1_linux_amd64.tar.gz"
      sha256 "c3a03c355f100f2cec1f4830509fa6d2261f6ba06ea032fbfab84919b12b53c5"
      def install
        bin.install "convoy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://dl.cloudsmith.io/public/convoy/convoy/raw/versions/25.7.1/convoy_25.7.1_linux_arm64.tar.gz"
      sha256 "03cc76609c3d5aaf6c263159f7329d1ea99334c9aed562dbedaf94738c62d710"
      def install
        bin.install "convoy"
      end
    end
  end
end
